apiVersion: v1
kind: Service
metadata:
  name: redis-control
  labels:
    app: redis
    role: control
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: control
    tier: backend
